<?= $this->insert('overall/cp/header') ?>

    <div class="content container-fluid">

      <div class="row row-broken">
        <div class="row row-broken">
          <div class="col-sm-6 col-md-3 col-lg-3 small-widget md-margin sm-margin m-t-md">
            <div id="ultra2" class="decor-default inform inform-view-1 inform-2">
              <div class="inform-value">13140 $</div>
              <div class="inform-name">Today Sales</div>
            </div>
          </div>
          <div class="col-sm-6 col-md-3 col-lg-3 small-widget md-margin left-md m-t-md p-r-none">
            <div id="ultra3" class="decor-default inform inform-view-1 inform-3">
              <div class="inform-value">9001</div>
              <div class="inform-name">Today Visitors</div>
            </div>
          </div>
          <div class="col-sm-6 col-md-3 col-lg-3 small-widget md-margin ultra-md m-t-md">
            <div id="ultra4" class="decor-default inform inform-view-1 inform-4">
              <div class="inform-value">350</div>
              <div class="inform-name">New message</div>
            </div>
          </div>
          <div class="col-sm-6 col-md-3 col-lg-3 small-widget md-margin ultra-md m-t-md">
            <div id="ultra6" class="decor-dim inform inform-view-2">
              <div class="inform-value">46%</div>
              <div class="inform-name">New users</div>
              <div id="inform-2" class="inform-canvas" data-percent="46">46%</div>
            </div>
          </div>
        </div>
    </div>

<?= $this->insert('overall/cp/footer') ?>
</body>
</html>
