<!-- pages-title-start -->

<section class="contact-img-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="con-text">
                    <h2 class="page-title"><?= $nombre ?></h2>
                    <p><a href="/brainscube/">Home</a> | <?= $name_min ?></p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- pages-title-end -->
