<?= $this->insert('overall/header',$data_header) ?>
<?= $this->insert('overall/header_no',$data_info) ?>
<!-- single peoduct content section start -->
<section class="single-product-area sit">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 none-si-pro">
                            <div class="pro-img-tab-content tab-content">
                              <?php for ($i=0; $i < count($producto->imgs); $i++) :?>
                                <?php $ac = ($i == 0)? 'active':'' ?>
                                <div class="tab-pane <?= $ac ?>" id="image-<?= $i ?>">
                                    <div class="simpleLens-big-image-container">
                                        <a class="simpleLens-lens-image" data-lightbox="roadtrip" data-lens-image="<?= $producto->imgs[$i] ?>">
                                            <img src="<?= $producto->imgs[$i] ?>" alt="<?= $producto->titulo ?>" class="simpleLens-big-image">
                                        </a>
                                    </div>
                                </div>
                              <?php endfor ?>
                            </div>
                            <div class="pro-img-tab-slider indicator-style2">
                              <?php for ($i=0; $i < count($producto->imgs); $i++) : ?>
                                <div class="item"><a href="#image-<?= $i ?>" data-toggle="tab"><img src="<?= $producto->imgs[$i] ?>" alt="<?= $producto->titulo ?>" /></a></div>
                              <?php endfor ?>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="cras">
                                <div class="product-name">
                                    <h2><?= $producto->titulo.' - '.$producto->marca ?></h2>
                                </div>
                                <div class="pro-rating cendo-pro">
                                    <div class="pro_one">
                                      <?php for ($s=0; $s < 5; $s++): ?>
                                        <?php if ($producto->rating[0] > $s) : ?>
                                            <i class="fa fa-star" style="color:gold;"></i>
                                        <?php else: ?>
                                          <i class="fa fa-star-o" style="color: #aaa;"></i>
                                        <?php endif ?>
                                      <?php endfor ?>
                                    </div>
                                    <p class="rating-links">
                                      <?php $s = ($producto->rating[1] == 1) ? '' : 's' ;?>
                                      <a href="#reseñas"><?= $producto->rating[1] ?> Reseña<?= $s ?></a>
                                    </p>
                                </div>
                                <p class="availability in-stock2">
                                  <?php $d = ($producto->stock[0]) ? 'Sí' : 'No' ; ?>
                                    <span>Disponible</span><strong>:</strong> <?= $d ?>
                                </p>
                                <div class="short-description">
                                    <p><?= $producto->descripcion[0] ?></p>
                                </div>
                                <div class="pre-box">
                                    <span class="special-price"><?= Articulo::dar_precio($producto->precio) ?></span>
                                </div>
                                <div class="add-to-box1">
                                    <div class="add-to-box add-to-box2">
                                        <div class="add-to-cart">
                                          <div class="input-content">
                                              <label>Quantity:</label>
                                              <div class="quantity">
                                                  <div class="cart-plus-minus">
                                                    <input type="text" value="0" name="qtybutton" class="cart-plus-minus-box">
                                                   </div>
                                              </div>
                                          </div>
                                            <div class="product-icon">
                                                <a href="#" >
                                                    <i class="fa fa-shopping-cart"></i>
                                                </a>
                                                <?php if ($producto->ch): ?>
                                                <a href="#" class="wishlist checked" data-product="<?= $producto->link ?>" data-checked="favorite">
                                                    <i class="fa fa-heart"></i>
                                                </a>
                                              <?php else: ?>
                                              <a href="#" class="wishlist" data-product="<?= $producto->link ?>" data-checked="no">
                                                  <i class="fa fa-heart"></i>
                                              </a>
                                              <?php endif ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-xs-12">
                            <div class="text">
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                    <li role="presentation" class="active">
                                        <a href="#home" aria-controls="home" role="tab" data-toggle="tab">Product Description</a>
                                    </li>
                                    <li role="presentation">
                                        <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Reseña<?= $s ?> (<?= $producto->rating[1] ?>)</a>
                                    </li>
                                </ul>
                                <!-- Tab panes -->
                                <div class="tab-content tab-con2">
                                    <div role="tabpanel" class="tab-pane active" id="home"><?= $producto->descripcion[1] ?></div>
                                    <div role="tabpanel" class="tab-pane" id="profile">
                                        <form class="form-horizontal" id="form_review">
                                            <div id="review">
                                                <table class="table table-striped table-bordered">
                                                  <?php if (!$producto->reviews) : ?>
                                                  <td colspan="3">
                                                    No hay ningúna reseña del producto.
                                                  </td>
                                                <?php else: ?>
                                                  <?php for ($i=0; $i < count($producto->reviews); $i++) : ?>
                                                    <tr>
                                                        <td style="width: 50%;">
                                                            <strong style="text-transform:capitalize;"><?= User::Datos('user',$producto->reviews[$i]['idusuario'])['user'] ?></strong>
                                                        </td>
                                                        <td class="text-right"><?= Strings::amigable_time($producto->reviews[$i]['date']) ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2">
                                                            <p class="text an-text"><?= $producto->reviews[$i]['comentario'] ?></p>
                                                            <?php for ($m=0; $m < 5; $m++) :?>
                                                              <?php if ($producto->reviews[$i]['rate']>$m) : ?>
                                                            <span class="fa fa-stack star">
                                                                <i class="fa fa-star fa-stack-2x star"></i>
                                                                <i class="fa fa-star-o fa-stack-2x star"></i>
                                                            </span>
                                                          <?php else: ?>
                                                            <span class="fa fa-stack star">
                                                                <i class="fa fa-star-o fa-stack-2x star"></i>
                                                                <i class="fa fa-star-o fa-stack-2x star"></i>
                                                            </span>
                                                          <?php endif ?>
                                                          <?php endfor ?>
                                                        </td>
                                                    </tr>
                                                  <?php endfor ?>
                                                <?php endif ?>
                                                </table>

                                            </div>
                                            <hr>
                                            <?php if (isset($_SESSION['app_id']) and !$posteado) : ?>
                                              <div class="alert alert-dismisable hide" id="ajax_review"></div>
                                                <div><fieldset class="rating" style="width:100%!important;text-align:left!important;">
                                                  <legend>Calificación:</legend>
                                                  <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="Rocks!" arial-hidden="true"></label>
                                                  <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good" arial-hidden="true"></label>
                                                  <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Meh" arial-hidden="true"></label>
                                                  <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Kinda bad" arial-hidden="true"></label>
                                                  <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Sucks big time"></label>
                                                </fieldset></div>
                                            <h2 class="write">Escribe una reseña</h2>
                                            <div class="form-group required">
                                                <div class="col-sm-12">
                                                    <label class="control-label" for="input-review">Comentario: </label>
                                                    <textarea id="input-review" class="form-control" rows="5" name="text"></textarea>
                                                    <input type="hidden" id="res" name="response" value="">
                                                    <input type="hidden" id="url" name="url" value="<?= $url ?>">
                                                    <input type="hidden" id="token" name="token" value="<?= $token ?>">
                                                    <div class="help-block">
                                                        <span class="text-danger">Nota:</span>
                                                        HTML no soportado. ! BBcode si !. No pongas palabras altisonantes.
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                               <label class="control-label">¿Eres robot? </label>
                                               <div class="col-sm-3"></div><div class="col-sm-9" id="captcha_container"></div>
                                            </div>


                                            <div class="buttons si-button">
                                                <div class="pull-right">
                                                    <button id="button-review" class="btn btn-primary" data-loading-text="Loading..." type="button">Continuar</button>
                                                </div>
                                            </div>
                                          <?php elseif (!$posteado): ?>
                                            <h3> ¿Quieres dejar tu reseña? </h3><br>
                                            <p>Puedes <a href="<?= __ROOT__.'login/='. $data_header['url'] ?>">iniciar sesión </a>
                                          <?php endif ?>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-sidebar">
                        <div class="single-sidebar an-shop">
                            <h3 class="wg-title">BEST SELLER</h3>
                            <ul>
                               <li class="b-none7">
                                    <div class="tb-recent-thumbb">
                                        <a href="">
                                            <img class="attachment" src="views/img/products/6.jpg" alt="">
                                        </a>
                                    </div>
                                    <div class="tb-recentb7">
                                        <div class="tb-beg">
                                            <a href="#">Lambskin Shoe</a>
                                        </div>
                                        <div class="tb-product-price font-noraure-3">
                                            <span class="amount">$180.00</span>
                                        </div>
                                    </div>
                                </li>
                                <li class="b-none7">
                                    <div class="tb-recent-thumbb">
                                        <a href="">
                                            <img class="attachment" src="views/img/products/10.jpg" alt="">
                                        </a>
                                    </div>
                                    <div class="tb-recentb7">
                                        <div class="tb-beg">
                                            <a href="#">Lambskin Shoe</a>
                                        </div>
                                        <div class="tb-product-price font-noraure-3">
                                            <span class="amount">$180.00</span>
                                        </div>
                                    </div>
                                </li>
                                <li class="b-none7">
                                    <div class="tb-recent-thumbb">
                                        <a href="">
                                            <img class="attachment" src="views/img/products/8.jpg" alt="">
                                        </a>
                                    </div>
                                    <div class="tb-recentb7">
                                        <div class="tb-beg">
                                            <a href="#">Lambskin Shoe</a>
                                        </div>
                                        <div class="tb-product-price font-noraure-3">
                                            <span class="amount">$180.00</span>
                                        </div>
                                    </div>
                                </li>
                                <li class="b-none7">
                                    <div class="tb-recent-thumbb">
                                        <a href="">
                                            <img class="attachment" src="views/img/products/9.jpg" alt="">
                                        </a>
                                    </div>
                                    <div class="tb-recentb7">
                                        <div class="tb-beg">
                                            <a href="#">Lambskin Shoe</a>
                                        </div>
                                        <div class="tb-product-price font-noraure-3">
                                            <span class="amount">$180.00</span>
                                        </div>
                                    </div>
                                </li>
                           </ul>
                        </div>
                        <div class="ro-info-box-wrap tpl3 st">
                            <div class="tb-image">
                                <img src="views/img/products/a1.jpg" alt="">
                            </div>
                            <div class="tb-content">
                                <div class="tb-content-inner an-inner">
                                    <h5>WOMEN'S FASHION</h5>
                                    <h3>MID SEASON SALE</h3>
                                    <h6>
                                        <a href="#">SHOP NOW</a>
                                    </h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<script src="https://www.google.com/recaptcha/api.js?onload=loadCaptcha&render=explicit" async defer></script>
<?= $this->insert('overall/footer') ?>
<script type='text/javascript' src="views/app/js/producto.js"></script>
<script type='text/javascript' src="views/app/js/wishlist.js"></script>
