<div class="footer">
© 2015 Copyright.
<ul class="footer-menu">
  <li><a href="#">Home</a></li>
  <li><a href="#">Dashboard</a></li>
  <li><a href="#">Reports</a></li>
  <li><a href="#">Support</a></li>
  <li><a href="#">Contact</a></li>
</ul>
</div>

</div>

<div id="wrap-menu" class="wrap-menu">
<span id="menu-btn-close" class="menu-btn-close">

  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 28 28"  xml:space="preserve">
    <g id="icon-close">
      <line x1="2" y1="2" x2="26" y2="26" />
      <line x1="2" y1="26" x2="26" y2="2" />
    </g>
  </svg>
</span>
<h1 class="menu-title">Navigation</h1>
<ul id="menu" class="menu">
<li id="menu-btn-back" class="back">
  <span>Back</span>
</li>
<li>
    <i class="fa fa-circle more"></i>
   <i class="fa fa-globe"></i>
  <span>Dashboards</span>
  <ul class="menu">
    <li><i class="fa fa-hashtag"></i><a href="index.html">Dashboard v1</a></li>
    <li><i class="fa fa-cube"></i><a href="dashboard2.html">Dashboard v2</a></li>
  </ul>
</li>

<li><i class="fa fa-font"></i><a href="typography.html">Typography</a></li>

<li>
 <i class="fa fa-circle more"></i>
 <i class="fa fa-desktop"></i>
  <span>Ui Kits</span>
  <ul class="menu">
    <li><i class="fa fa-code-fork"></i><span class="label label-alt label-xs label-success">New!</span><a href="blocks.html">Blocks</a></li>
    <li><i class="fa fa-square"></i><span class="label label-alt label-xs label-success">New!</span><a href="box-shadow.html">Box-shadow</a></li>
    <li><i class="fa fa-briefcase"></i><a href="buttons.html">Buttons</a></li>
    <li><i class="fa fa-check-circle-o"></i><a href="checkboxes.html">Checkboxes</a></li>
    <li><i class="fa fa-check-circle"></i><span class="label label-alt label-xs label-success">New!</span><a href="checkboxes2.html">Checkboxes v2</a></li>
    <li><i class="fa fa-diamond"></i><a href="dialogs.html">Dialogs</a></li>
    <li><i class="fa fa-check-circle-o"></i><span class="label label-alt label-xs label-success">New!</span><a href="dialog-notification.html">Dialog notification</a></li>
    <li><i class="fa fa-object-group"></i><span class="label label-alt label-xs label-success">New!</span><a href="general_ui.html">General UI</a></li>
    <li><i class="fa fa-code"></i><a href="grid.html">Grid Options</a></li>
    <li><i class="fa fa-usb"></i><span class="label label-alt label-xs label-success">New!</span><a href="icons.html">Icons</a></li>
    <li><i class="fa fa-tags"></i><span class="label label-alt label-xs label-success">New!</span><a href="labels.html">Labels</a></li>
    <li><i class="fa fa-spinner"></i><a href="loading.html">Loading effect</a></li>
    <li><i class="fa fa-bell"></i><a href="notification.html">Notifications</a></li>
    <li><i class="fa fa-columns"></i><span class="label label-alt label-xs label-success">New!</span><a href="panels.html">Panels</a></li>
    <li><i class="fa fa-magic"></i><a href="wizard.html">Wizard</a></li>
  </ul>
</li>

<li>
   <i class="fa fa-circle more"></i>
   <i class="fa fa-th"></i>
  <span>Forms</span>
  <ul class="menu">
    <li><i class="fa fa-folder-open-o"></i><span class="label label-alt label-xs label-success">New!</span><a href="form-components.html">Form components</a></li>
    <li><i class="fa fa-share"></i><span class="label label-alt label-xs label-success">New!</span><a href="form-elements.html">Form Elements</a></li>
    <li><i class="fa fa-database"></i><span class="label label-alt label-xs label-success">New!</span><a href="form-examples.html">Form Examples</a></li>
    <li><i class="fa fa-compass"></i><span class="label label-alt label-xs label-success">New!</span><a href="form-validation.html">Form Validation</a></li>
    <li><i class="fa fa-keyboard-o"></i><a href="input.html">Input Fields</a></li>
  </ul>
</li>

<li>
   <i class="fa fa-circle more"></i>
   <i class="fa fa-paint-brush"></i>
  <span>Colors</span>
  <ul class="menu">
    <li><i class="fa fa-paint-brush"></i><a href="index.html">Default Skin</a></li>
    <li><i class="fa fa-paint-brush"></i><a href="index-light.html">Light Skin</a></li>
    <li><i class="fa fa-paint-brush"></i><a href="index-dark.html">Dark Skin</a></li>
    <li><i class="fa fa-paint-brush"></i><a href="index-dim.html">Dim Skin</a></li>
  </ul>
</li>

<li>
   <i class="fa fa-circle more"></i>
   <i class="fa fa-pencil"></i>
  <span>Editors</span>
  <ul class="menu">
    <li><i class="fa fa-pencil"></i><span class="label label-alt label-xs label-success">New!</span><a href="bootstrap-wysiwyg.html">Bootstrap Wysiwyg</a></li>
    <li><i class="fa fa-pencil"></i><span class="label label-alt label-xs label-success">New!</span><a href="summernote.html">Summernote</a></li>
    <li><i class="fa fa-pencil"></i><span class="label label-alt label-xs label-success">New!</span><a href="tinymce.html">TinyMCE</a></li>
  </ul>
</li>

<li>
 <i class="fa fa-circle more"></i>
 <i class="fa fa-envelope-o"></i>
  <span>E-mail</span>
  <ul class="menu">
    <li><i class="fa fa-list-ul"></i><a href="email-list.html">Email list</a></li>
    <li><i class="fa fa-inbox"></i><a href="email-inbox.html">Email inbox</a></li>
    <li><i class="fa fa-paper-plane-o"></i><a href="email-send.html">Email send</a></li>
  </ul>
</li>

<li>
   <i class="fa fa-circle more"></i>
   <i class="fa fa-server"></i>
  <span>Contacts</span>
  <ul class="menu">
    <li><i class="fa fa-mobile"></i><a href="contacts.html">Contact list</a></li>
    <li><i class="fa fa-phone"></i><a href="contact.html">Contact preview</a></li>
  </ul>
</li>

<li>
  <i class="fa fa-th-list"></i>
  <a href="widgets.html">Widgets</a>
</li>

<li>
   <i class="fa fa-circle more"></i>
   <i class="fa fa-music"></i>
  <span>Media</span>
  <ul class="menu">
    <li><i class="fa fa-crop"></i><a href="crop.html">Crop</a></li>
    <li><i class="fa fa-picture-o"></i><a href="gallery.html">Gallery</a></li>
    <li><i class="fa fa-camera-retro"></i><a href="slider.html">Sliders</a></li>
  </ul>
</li>

<li>
   <i class="fa fa-circle more"></i>
   <i class="fa fa-table"></i>
  <span>Tables</span>
  <ul class="menu">
    <li><i class="fa fa-th"></i><span class="label label-alt label-xs label-success">New!</span><a href="tables.html">Tables</a></li>
    <li><i class="fa fa-table"></i><span class="label label-alt label-xs label-success">New!</span><a href="datatables.html">Datatables</a></li>
    <li><i class="fa fa-expand"></i><span class="label label-alt label-xs label-success">New!</span><a href="responsive-table.html">Responsive table</a></li>
  </ul>
</li>

<li>
   <i class="fa fa-circle more"></i>
   <i class="fa fa-newspaper-o"></i>
  <span>News</span>
  <ul class="menu">
    <li><i class="fa fa-newspaper-o"></i><span class="label label-alt label-xs label-success">New!</span><a href="news.html">News</a></li>
    <li><i class="fa fa-newspaper-o"></i><span class="label label-alt label-xs label-success">New!</span><a href="news-v2.html">News-v2</a></li>
    <li><i class="fa fa-newspaper-o"></i><span class="label label-alt label-xs label-success">New!</span><a href="news-v3.html">News-v3</a></li>
    <li><i class="fa fa-newspaper-o"></i><span class="label label-alt label-xs label-success">New!</span><a href="news-v4.html">News-v4</a></li>
  </ul>
</li>

<li>
   <i class="fa fa-circle more"></i>
   <i class="fa fa-key"></i>
  <span>Sample pages</span>
  <ul class="menu">
    <li><i class="fa fa-calendar"></i><a href="calendar.html">Calendar</a></li>
    <li><i class="fa fa-comment-o"></i><a href="chat.html">Chat</a></li>
    <li><i class="fa fa-sliders"></i><a href="filter.html">Filter</a></li>
    <li><i class="fa fa-clock-o"></i><a href="timeline.html">Timeline</a></li>
    <li><i class="fa fa-list-ul"></i><a href="todo.html">Todo</a></li>
    <li><i class="fa fa-sign-in"></i><a href="login.html">Log in</a></li>
    <li><i class="fa fa-unlock-alt"></i><a href="lostpassword.html">Recovery password</a></li>
    <li><i class="fa fa-book"></i><a href="register.html">Register</a></li>
    <li><i class="fa fa-user"></i><a href="profile.html">Profile</a></li>
    <li><i class="fa fa-flag"></i><span class="label label-alt label-xs label-success">New!</span><a href="timer.html">Timer</a></li>
    <li><i class="fa fa-flag"></i><span class="label label-alt label-xs label-success">New!</span><a href="timer2.html">Timer 2</a></li>
  </ul>
</li>

<li>
 <i class="fa fa-circle more"></i>
 <i class="fa fa-exclamation-triangle"></i>
  <span>Error pages</span>
  <ul class="menu">
    <li><i class="fa fa-exclamation-triangle"></i><a href="403.html">403</a></li>
    <li><i class="fa fa-exclamation-triangle"></i><a href="404.html">404</a></li>
    <li><i class="fa fa-exclamation-triangle"></i><a href="500.html">500</a></li>
  </ul>
</li>

<li>
 <i class="fa fa-circle more"></i>
 <i class="fa fa-file"></i>
  <span>Layouts</span>
  <ul class="menu">
    <li><i class="fa fa-file"></i><span class="label label-alt label-xs label-success">New!</span><a href="blank.html">Blank page</a></li>
    <li><i class="fa fa-file"></i><span class="label label-alt label-xs label-success">New!</span><a href="nosidebar-left.html">No left sidebar</a></li>
    <li><i class="fa fa-file"></i><span class="label label-alt label-xs label-success">New!</span><a href="nosidebar-right.html">No right sidebar</a></li>
    <li><i class="fa fa-file"></i><span class="label label-alt label-xs label-success">New!</span><a href="nosidebars.html">No both sidebars</a></li>
    <li><i class="fa fa-file"></i><span class="label label-alt label-xs label-success">New!</span><a href="boxed.html">Boxed layout</a></li>
  </ul>
</li>

<li>
 <i class="fa fa-area-chart"></i>
  <a href="charts.html">Charts</a>
</li>

<li>
 <i class="fa fa-flask"></i>
 <span class="label label-alt label-xs label-success">New!</span>
  <a href="generic-classes.html">Generic classes</a>
</li>
</ul>
</div>

<div id="overlay" class="overlay"></div>




<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.nicescroll.min.js"></script>
<script src="js/classie.js"></script>
<script src="js/bootstrap-select.min.js"></script>
<script src="js/search.js"></script>
<script src="js/sweetalert.min.js"></script>
<script src="js/moment.min.js"></script>
<script src="js/polyfill.object-fit.min.js"></script>

<script src="js/ui.js"></script>



<script src="js/jquery.easypiechart.min.js"></script>
<script src="js/jquery.sparkline.min.js"></script>
<script src="js/calendar.js"></script>
<script type="text/javascript">
$(document).ready(function () {
  $('#inform-1').easyPieChart({
    barColor: '#f2a654',
    trackColor: '#8a78a5',
    scaleColor: false,
    lineWidth: 6,
    size: 60,
    animate: 1000
  });
  $('#inform-2').easyPieChart({
    barColor: '#8a78a5',
    trackColor: '#dc8079',
    scaleColor: false,
    lineWidth: 6,
    size: 60,
    animate: 1000
  });
});
</script>
<script src="js/chart.js"></script>
<script>
Chart.defaults.global.animationEasing = "easeOutBounce";
Chart.defaults.global.pointLabelFontSize = 12;
Chart.defaults.global.responsive = true;
Chart.defaults.global.maintainAspectRatio = false;

var lineChartData = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      label: "Warning",
      fillColor: "#f2a654",
      strokeColor: "#f2a654",
      pointColor: "#f2a654",
      data: [23, 41, 35, 48, 45, 34, 37]
            },
    {
      label: "Success",
      fillColor: "#46be8a",
      strokeColor: "#46be8a",
      pointColor: "#46be8a",
      data: [13, 35, 30, 43, 37, 27, 30]
            },
    {
      label: "Default",
      fillColor: "#a28cc1",
      strokeColor: "#a28cc1",
      pointColor: "#a28cc1",
      data: [10, 21, 24, 34, 26, 17, 20]
            },
        ]
}

var lineChartData2 = {
  labels: [1, 2, 3, 4, 5, 6, 7],
  datasets: [
    {
      label: "Default",
      fillColor: "#7266ba",
      strokeColor: "#7266ba",
      pointColor: "#7266ba",
      data: [23, 41, 35, 48, 45, 34, 37]
            }
        ]
}

var barChartData = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      fillColor: "#a28cc1",
      highlightFill: "#8c79a6",
      data: [10, 21, 58, 64, 21, 35, 55]
            },
    {
      fillColor: "#f2a654",
      highlightFill: "#f2a654",
      data: [13, 25, 10, 68, 10, 2, 46]
            }
        ]

}
var cm3Data = {
  labels: ["1", "2", "3", "4", "5", "6", "7"],
  datasets: [
    {
      label: "Default",
      fillColor: "transparent",
      strokeColor: "#ffffff",
      pointColor: "#7266ba",
      pointStrokeColor: "#ffffff",
      data: [5, 0, 10, 20, 15, 20, 20]
            }
        ]
};
var cm4Data = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      fillColor: "#ffffff",
      highlightFill: "#7266ba",
      data: [10, 21, 58, 64, 21, 35, 55]
            }
        ]

};
var cm5Data = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      label: "Default",
      fillColor: "#a28cc1",
      strokeColor: "#a28cc1",
      pointColor: "#a28cc1",
      data: [23, 41, 35, 48, 45, 34, 37]
            }
        ]
};
var cl1Data = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      label: "Default",
      fillColor: "transparent",
      strokeColor: "#ff948c",
      pointColor: "#ff948c",
      data: [5, 10, 15, 25, 22, 20, 25]
            },
    {
      label: "Success",
      fillColor: "transparent",
      strokeColor: "#f2a654",
      pointColor: "#f2a654",
      data: [0, 5, 8, 17, 20, 25, 30]
            }
        ]
};
var cl2Data = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      label: "Default",
      fillColor: "#46be8a",
      strokeColor: "#46be8a",
      pointColor: "#46be8a",
      data: [8, 10, 14, 12, 10, 12, 14]
            },
    {
      label: "Default",
      fillColor: "#a28cc1",
      strokeColor: "#a28cc1",
      pointColor: "#a28cc1",
      data: [5, 8, 12, 10, 8, 10, 12]
            }
        ]
};

window.onload = function () {
  var ctxLine = document.getElementById("chartLine").getContext("2d");
  var ctxBar = document.getElementById("chartBar").getContext("2d");
  var cm3 = document.getElementById("chart-mini-3").getContext("2d");
  var cm4 = document.getElementById("chart-mini-4").getContext("2d");
  var cm5 = document.getElementById("chart-mini-5").getContext("2d");
  var cl1 = document.getElementById("cl1").getContext("2d");
  var cl2 = document.getElementById("cl2").getContext("2d");
  var ctxLine2 = document.getElementById("chartLine2").getContext("2d");

  window.myLine = new Chart(ctxLine).Line(lineChartData, {
    showScale: false,
    pointDot: false
  });

  window.myBar = new Chart(ctxBar).Bar(barChartData, {
    showScale: false,
    barShowStroke: false,
    barValueSpacing: 0,
    barDatasetSpacing: 0
  });

  window.myLine = new Chart(cm3).Line(cm3Data, {
    showScale: false,
    pointDotStrokeWidth: 3,
    bezierCurve: false
  });

  window.myBar = new Chart(cm4).Bar(cm4Data, {
    showScale: false,
    barShowStroke: false,
    barValueSpacing: 50,
    barDatasetSpacing: 0
  });

  window.myLine = new Chart(cm5).Line(cm5Data, {
    showScale: false,
    pointDot: false,
    bezierCurve: false
  });

  window.myLine = new Chart(cl1).Line(cl1Data, {
    showScale: false,
    pointDot: false,
    bezierCurve: false
  });

  window.myLine = new Chart(cl2).Line(cl2Data, {
    showScale: false,
    pointDot: false,
    bezierCurve: false
  });

  window.myLine = new Chart(ctxLine2).Line(lineChartData2, {
    showScale: false,
    pointDot: false,
    bezierCurve: true,
    showTooltips: false
  });
};
</script>
<script>
$(document).ready(function () {
  $("#calendar-mini").zabuto_calendar({
    today: true,
    weekstartson: 0,
    legend: [
      {
        type: "text",
        label: "Meet your friends today",
        badge: "11:30"
                },
      {
        type: "text",
        label: "Tweet “thanks” for your followers",
        badge: "21:00"
                }
            ]
  });

  $(".legend-text").wrap("<a href='todo.html'></a>");
});
</script>
<script src="js/skycons.js"></script>
<script>
var skycons = new Skycons({
  "color": "white"
});
skycons.add("icon1", Skycons.PARTLY_CLOUDY_DAY);
skycons.add("icon2", Skycons.CLEAR_DAY);
skycons.play();
</script>
<script src="js/jquery.nicescroll.min.js"></script>
<script src="js/TweenMax.min.js"></script>
<script src="js/chat.js"></script>
<script src="js/peppermint.min.js"></script>
<script>
$(".chat-messages").niceScroll();

$('.team-body').Peppermint({
  dots: true
});

//UltraWidget
  function dynamicWidget(id, time, number, attr) {
    setTimeout(function(){
    $("#" + id).prop('Counter',0).animate({
          Counter: number
      }, {
          duration: time,
          step: function (now) {
            if(attr){
              $("#" + id + " .inform-value").text(Math.ceil(now) + attr);
            }
            else{
              $("#" + id + " .inform-value").text(Math.ceil(now));
            }
          }
      });
    }, 350);
  };

  function slowCount(id, number, time) {
    setTimeout(function(){
    var n = +number;
      setInterval(
        function(){
          $("#" + id + " .inform-value").text(n++);
        }, time
      );
    }, 2500);
  };



  dynamicWidget("ultra1", 2000, 400);
  dynamicWidget("ultra2", 2000, 13140, " $");
  dynamicWidget("ultra3", 2000, 9001);
  dynamicWidget("ultra4", 2000, 350);
  dynamicWidget("ultra5", 6000, 74, " %");
  dynamicWidget("ultra6", 14000, 46, " %");

  slowCount("ultra1", 400 , 2000);
  slowCount("ultra3", 9001 , 3300);

$("#sparkpie").sparkline([4, 6, 4, 2], {
    type: 'pie',
    width: '46px',
    height: '46px',
    sliceColors: ["#39bfe8", "#46be8a", "#f2a654", "#7266ba"]
  });

  $("#sparkpie2").sparkline([4, 8, 4, 5], {
    type: 'pie',
    width: '46px',
    height: '46px',
    sliceColors: ["#ff64b0", "#46be8a", "#f2a654", "#7266ba"]
  });

  $("#sparkchart-3").sparkline([7, 8, 12, 9, 11, 10, 9], {
    type: 'bar',
    barColor: "#7266ba",
    barWidth: '6px',
    barSpacing: '3px',
    height: "40px"
  });

  $("#sparkchart-4").sparkline([7, 8, 12, 9, 11, 10, 9], {
    type: 'line',
    height: "40px",
    width: "60px",
    spotRadius: 0,
    fillColor: "#7266ba",
    lineColor: "#7266ba",
    highlightLineColor: "#f2a654"
  });

  $("#sparkchart-5").sparkline([8, 13, 6, 11, 8, 9, 10, 12], {
    type: 'line',
    height: "40px",
    width: "60px",
    spotRadius: 0,
    lineWidth: 2,
    fillColor: "#fff",
    lineColor: "#7266ba",
    highlightLineColor: "#f2a654"
  });


  $("#sparkchart-6").sparkline([8, 5, 13, 6, 9, 10, 4], {
    type: 'bar',
    barColor: "#7266ba",
    barWidth: '6px',
    barSpacing: '3px',
    height: "40px"
  });
</script>
