<?= $this->insert('overall/header',$data_header) ?>
<?= $this->insert('overall/header_no',$data_info) ?>
<section class="pages products-page section-padding-top">
  <div class="container">
    <h1>La solicitud no se pudo completar</h1>
    <p>La página <strong><?= $req ?></strong> no se ha encontrado. Verifica que esté correctamente escrito.<br> O ve a la página de <a href="<?= __ROOT__ ?>">inicio</a></p>
  </div>
</div>
<?= $this->insert('overall/footer') ?>
