<?= $this->insert('overall/header',$data_header) ?>
<?= $this->insert('overall/header_no',$data_info) ?>

<!-- wishlist content section start -->
<div class="shopping-cart-area nr-wish-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="s-cart-all">
                        <div class="cart-form table-responsive">
                            <table id="shopping-cart-table" class="data-table cart-table">
                                <tr>
                                    <th class="low1"></th>
                                    <th>Images</th>
                                    <th class="low2">Product Name</th>
                                    <th>Unit Price </th>
                                    <th>Stock Status</th>
                                    <th class="low5"></th>
                                </tr>
                                <tr>
                                    <td class="sop-icon1">
                                        <a href="#">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </td>
                                    <td class="sop-cart">
                                        <a href="#"><img class="primary-image" alt="" src="views/img/products/10.jpg"></a>
                                    </td>
                                    <td class="sop-cart an-sh">
                                        <div class="tb-beg">
                                            <a href="#">Vintage Shoe</a>
                                        </div>
                                        <div class="last-cart l-mrgn">
                                            <a class="las4" href="#">Quick View</a>
                                        </div>
                                    </td>
                                    <td class="sop-cart">
                                        <div class="tb-product-price font-noraure-3">
                                            <span class="amount">$180.00</span>
                                        </div>
                                    </td>
                                    <td class="cen">
                                        <span class="wishlist-in-stock">In Stock</span>
                                    </td>
                                    <td class="sop-cart">
                                        <div class="last-cart l-mrgn wish">
                                            <a class="las4" href="#"> Add to Cart</a>
                                        </div>
                                    </td>
                                </tr>
                                <tfoot>
                                    <tr>
                                        <td colspan="6">
                                            <div class="yith-wcwl-share">
                                                <div class="as">
                                                    <h4 class="yith-wcwl-share-title">Share on:</h4>
                                                </div>
                                                <ul>
                                                    <li><a href="#"><img src="views/img/icon-img/facebook.png" alt=""></a></li>
                                                    <li><a href="#"><img src="views/img/icon-img/twitter.png" alt=""></a></li>
                                                    <li><a href="#"><img src="views/img/icon-img/pinterest.jpg" alt=""></a></li>
                                                    <li><a href="#"><img src="views/img/icon-img/googleplus.jpg" alt=""></a></li>
                                                    <li><a href="#"><img src="views/img/icon-img/email.jpg" alt=""></a></li>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- wishlist  content section end -->

<?= $this->insert('overall/footer') ?>
