<?= $this->insert('overall/header',$data_header) ?>
<?= $this->insert('overall/header_no',$data_info) ?>

<!-- wishlist content section start -->
<div class="shopping-cart-area nr-wish-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="s-cart-all">
                        <div class="cart-form table-responsive">
                            <table id="shopping-cart-table" class="data-table cart-table">
                                <tr>
                                    <th class="low1"></th>
                                    <th>Imágen</th>
                                    <th class="low2">Nombre del producto </th>
                                    <th>Precio unitario </th>
                                    <th>cantidad </th>
                                    <th class="low5">Total</th>
                                </tr>
                                <!-- Single product start -->
                                <?php if (isset($tienda->productos)): ?>
                                  <?php $d_button = ""; ?>
                                  <?php for ($i=0; $i < count($tienda->productos->index); $i++) : ?>
                                  <tr>
                                      <td class="sop-icon1">
                                          <a href="#" class="carro" data-checked="favorite" data-w="wh" data-product="<?= $tienda->productos->datos[$i]->link ?>">
                                              <i class="fa fa-times"></i>
                                          </a>
                                      </td>
                                      <td class="sop-cart">
                                          <a href="tienda/producto/<?= $tienda->productos->datos[$i]->link ?>"><img class="primary-image" alt="" src="<?= $tienda->productos->datos[$i]->imagen ?>"></a>
                                      </td>
                                      <td class="sop-cart an-sh">
                                          <div class="tb-beg">
                                              <a href="tienda/producto/<?= $tienda->productos->datos[$i]->link ?>"><?= $tienda->productos->datos[$i]->titulo ?></a>
                                          </div>
                                          <!--<div class="last-cart l-mrgn">
                                              <a class="las4" href="#">Quick View</a>
                                          </div>-->
                                      </td>
                                      <td class="sop-cart">
                                          <div class="tb-product-price font-noraure-3">
                                              <span class="amount"><?= Articulo::dar_precio($tienda->productos->datos[$i]->precio) ?></span>
                                          </div>
                                      </td>
                                      <td class="cen">
                                        <?= $tienda->productos->cantidad[$i] ?>
                                      </td>
                                      <td class="sop-cart">
                                          <?= Articulo::dar_precio($tienda->productos->cantidad[$i]*$tienda->productos->datos[$i]->precio) ?>
                                      </td>
                                  </tr>
                                <?php endfor ?>
                              <?php else: ?>
                                <?php $d_button = "disabled"; ?>
                                <tr>
                                    <td colspan="6">
                                        <h3> No hay productos en tu carrito de compra </h3>
                                        <p>Pero puedes ir a la <a href="tienda/">tienda</a> para revisar nuestros productos.</p>
                                    </td>
                                </tr>
                              <?php endif ?>
                                <!-- Single product end -->
                                <tfoot>
                                    <tr>
                                        <td colspan="4"></td>
                                        <td colspan="2"><button class="btn btn-primary" <?= $d_button ?>>Hacer pedido</button></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- wishlist  content section end -->

<?= $this->insert('overall/footer') ?>
