
<!-- brand section start -->
<section class="section-padding-top">
   <div class="brand-logo">
<div class="barnd-bg">
  <div class="container">
    <div class="row text-center">
      <div id="brand-logo" class="re-owl-carousel21 owl-carousel product-slider owl-theme">
        <div class="col-xs-12">
          <div class="single-brand">
            <a href="#"><img src="views/img/brand/1.png" alt="" /></a>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="single-brand">
            <a href="#"><img src="views/img/brand/2.png" alt="" /></a>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="single-brand">
            <a href="#"><img src="views/img/brand/3.png" alt="" /></a>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="single-brand">
            <a href="#"><img src="views/img/brand/4.png" alt="" /></a>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="single-brand">
            <a href="#"><img src="views/img/brand/5.png" alt="" /></a>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="single-brand">
            <a href="#"><img src="views/img/brand/6.png" alt="" /></a>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="single-brand">
            <a href="#"><img src="views/img/brand/1.png" alt="" /></a>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="single-brand">
            <a href="#"><img src="views/img/brand/3.png" alt="" /></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</section>
<!-- brand section end -->
<!-- service section start -->
<section class="re-section-padding">
<div class="service section-padding">
<div class="container">
  <div class="row text-center">
    <div class="col-xs-12 col-sm-4">
      <div class="single-service">
        <i class="pe-7s-plane"></i>
        <h4>Envio Gratis</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="single-service res-single">
        <i class="pe-7s-headphones"></i>
        <h4>Ayuda a nustros clientes</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="single-service">
        <i class="fa fa-bullhorn" arial-hidden="true"></i>
        <h4>Siempre los mejores productos</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </div>
  </div>
</div>
</div>
</section>
<!-- service section end -->
<!-- footer section start -->
<footer class="re-footer-section">
<!-- footer-top area start -->
<div class="footer-top section-padding-top">
<div class="footer-dsc">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="single-text res-text">
          <div class="footer-title">
            <h4>Contacto</h4>
            <hr class="dubble-border"/>
          </div>
          <div class="footer-text">
            <ul>
              <li>
                <i class="pe-7s-map-marker"></i>
                <p>Local L-302 Frikiplaza (bazar del entretenimiento y el video juego). Eje Central Lázaro Cárdenas número 9, Colonia Centro</p>
                <p class="rs">Delegación Cuahutemoc 06000 Mexico City, Mexico</p>
              </li>
              <li>
                <i class="pe-7s-call"></i>
                <p>5512 6338</p>
              </li>
              <li>
                <i class="pe-7s-mail-open"></i>
                <p>info@brainscube.com</p>
                <p>contacto@brainscube.com</p>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="single-text res-text">
          <div class="footer-title">
            <h4>Mi cuenta</h4>
            <hr class="dubble-border"/>
          </div>
          <div class="footer-menu">
            <ul>
              <li><a href="account/">Mi cuenta</a></li>
              <li><a href="wishlist/">Lista de deseos</a></li>
              <li><a href="orders/">Mis pedidos</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3 margin-top">
        <div class="single-text res-text">
          <div class="footer-title">
            <h4>Servicio al cliente</h4>
            <hr class="dubble-border"/>
          </div>
          <div class="footer-menu">
            <ul>
              <li><a href="contacto">Contacto</a></li>
              <li><a href="devoluciones">Devoluciones</a></li>
              <li><a href="marcas">Marcas</a></li>
              <li class="nm"><a href="promos">Promociones</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xs-12 hidden-sm col-md-3 margin-top">
        <div class="single-text res-text">
          <div class="footer-title">
            <h4>Prroteccion a tus datos</h4>
            <hr class="dubble-border"/>
          </div>
          <div class="footer-text" style="text-aling:center;">
            <img src="https://knowledge.rapidssl.com/library/VERISIGN/ALL_OTHER/Frank/RapidSSL_SEAL-90x50.gif" style="margin:auto;width:90px;"/>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr class="dubble-border"/>
</div>
<div class="social-media">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="paypal social-icon">
          <ul>
            <li><a><i class="fa fa-cc-paypal"></i></a></li>
            <li><a><i class="fa fa-oxxo"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="social-icon">
          <ul class="floatright">
            <li class="res-mar"><a href="https://www.facebook.com/BrainsCube"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- footer-top area end -->
<!-- footer-bottom area start -->
<div class="footer-bottom">
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
      <p><?php echo APP_COPY; ?> Todos los derechos reservados.</p>
    </div>
  </div>
</div>
</div>
<!-- footer-bottom area end -->
</footer>
<!-- footer section end -->

<!-- all js here -->
<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
<?php if (true == DEBUG): ?>
<script src="views/app/js/jdev.js"></script>
<?php else: ?>
<script src="views/app/js/jquery.js"></script>
<?php endif ?>
<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
<!-- bootstrap js -->
<script src="views/js/bootstrap.min.js"></script>
<!-- parallax js -->
<script src="views/js/parallax.min.js"></script>
<!-- bundle -->
<script src="views/js/typeahead.bundle.js"></script>
<!-- owl.carousel js -->
<script src="views/js/owl.carousel.min.js"></script>
<!-- Img Zoom js -->
<script src="views/js/img-zoom/jquery.simpleLens.min.js"></script>
<!-- meanmenu js -->
<script src="views/js/jquery.meanmenu.js"></script>
<!-- jquery.countdown js -->
<script src="views/js/jquery.countdown.min.js"></script>
<!-- Nivo slider js
============================================ -->
<script src="views/lib/js/jquery.nivo.slider.js" type="text/javascript"></script>
<script src="views/lib/home.js" type="text/javascript"></script>
<!-- jquery-ui js -->
<script src="views/js/jquery-ui.min.js"></script>
<!-- sticky js -->
<script src="views/js/sticky.js"></script>
<!-- plugins js -->
<script src="views/js/plugins.js"></script>
<!-- handlebars js -->
<script src="views/js/handlebars.js"></script>
<!-- bootbox js -->
<script src="views\app\js\bootbox.min.js"></script>
<!-- main js -->
<script src="views/js/main.js"></script>


<script type='text/javascript' src="views/app/js/wishlist.js"></script>
<script type='text/javascript' src="views/app/js/carro.js"></script>

<script src="views/app/js/login.js"></script>
<script src="views/app/js/register.js"></script>
